extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
  syslog:
     tcp:
       listen_address: "0.0.0.0:54527"
     protocol: rfc3164
     location: UTC
     operators:
       - type: move
         from: attributes.message
         to: body
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

processors:
  batch:

exporters:
  logging:
    verbosity: detailed
  otlp/elastic:
    endpoint: "b09088f128a843869623c860b4765863.apm.us-central1.gcp.cloud.es.io:443"
    headers:
      Authorization: "Bearer hY"
        
service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,otlp/elastic]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,otlp/elastic]

    logs:
      receivers: [syslog]
      processors: [batch]
      exporters: [otlp/elastic]
  extensions: [health_check, pprof, zpages]
